In [1]:
import torch

$y = 3 x^3$

$\frac{dy}{dx} = 3 \times 3 x^2$

In [2]:
x = torch.tensor([2], dtype=torch.float32, requires_grad=True)

In [3]:
y = 3 * x ** 3

In [4]:
y.backward()

In [5]:
x.grad

tensor([36.])

In [6]:
x1 = torch.tensor([4], dtype=torch.float32, requires_grad=True)
x2 = torch.tensor([2], dtype=torch.float32, requires_grad=True)

In [7]:
y = 2 * x1 ** 2 + 3 * x2 ** 3

In [8]:
y.backward()

In [9]:
x1.grad

tensor([16.])

In [10]:
x2.grad

tensor([36.])